version: '3'

services:
  backend-barterkita:
    build: .
    ports:
      - "3999:3999"
    environment:
      - NODE_ENV=production
      - PORT=3999
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge