version: '3'

services:
  backend-barterkita:
    container_name: backend-barterkita
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3999:3999"
    environment:
      - NODE_ENV=production
      - PORT=3999
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true